### ISSUE TITLE
Unnecessary copying of vector?

### ISSUE THREAD

**Issue by wetling** [wetling/DirkQuest#2]
When Screen.cpp prints the board using the printLevel() function, it copies a vector from Level.cpp using Level.cpp's getData() function. Copying a large vector uses an unnecessary amount of processing time. Any ideas for how to optimize this?

**Comment by knedlsepp** [comment]
You can always return reference to const instead: `const std::vector<std::string>& getData() { return _levelData; }`

**Comment by wetling** [comment]
This would allow me to access the vector directly from another class?

**Comment by knedlsepp** [comment]
Yes. With a guarantee on read-only access.

**Comment by wetling** [comment]
Good to know.
Thanks for your help!
